version: '3.5'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - PGHOST=db
    image: postgres:16-alpine
    volumes:
      - ./db/dump:/home/db/dump
      - ./db/storage:/var/lib/postgresql/data:rw
  api:
    container_name: api
    ports:
      - 8000:8000
    build:
      context: ./docker/api
      dockerfile: ./Dockerfile
    volumes:
        - ./api:/usr/src/api
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    tty: true
