"""update

Revision ID: 370a0ba8c6c3
Revises: 
Create Date: 2024-10-10 16:11:56.287729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370a0ba8c6c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), server_default=sa.text('USER'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('interface_object_id', sa.UUID(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interface_object_id'], ['interface_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bounding_contours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('basic_object_id', sa.UUID(), nullable=False),
    sa.Column('is_assembly', sa.Boolean(), nullable=False),
    sa.Column('brep_files', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['basic_object_id'], ['basic_objects.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['bounding_contours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basic_object_id')
    )
    op.create_table('parent_child_association',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['basic_objects.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['basic_objects.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_child_association')
    op.drop_table('bounding_contours')
    op.drop_table('basic_objects')
    op.drop_table('interface_objects')
    # ### end Alembic commands ###
