"""new 

Revision ID: 9565cf09900d
Revises: 6705e314be55
Create Date: 2025-01-09 15:02:05.323195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9565cf09900d'
down_revision: Union[str, None] = '6705e314be55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('interface_object_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'modules', 'interface_objects', ['interface_object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'interface_object_id')
    # ### end Alembic commands ###
