"""role

Revision ID: 12faf919aaee
Revises: 2659f322ad93
Create Date: 2025-01-15 17:29:06.033703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12faf919aaee'
down_revision: Union[str, None] = '2659f322ad93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_child_module', sa.Column('child_role', sa.String(), nullable=True))
    op.add_column('parent_child_module', sa.Column('child_role_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_child_module', 'child_role_description')
    op.drop_column('parent_child_module', 'child_role')
    # ### end Alembic commands ###
