"""new db

Revision ID: 6705e314be55
Revises: 
Create Date: 2025-01-09 14:36:07.966408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6705e314be55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ttx', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ttx', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_boundaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interface_id_in', sa.UUID(), nullable=True),
    sa.Column('interface_id_out', sa.UUID(), nullable=True),
    sa.Column('stream_id', sa.UUID(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('ttx', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interface_id_in'], ['interface_objects.id'], ),
    sa.ForeignKeyConstraint(['interface_id_out'], ['interface_objects.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('author', sa.String(), server_default=sa.text('USER'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ttx', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('implementation', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SKETCH', 'PROTOTYPE', 'RELEASE', name='modulestatus'), nullable=False),
    sa.Column('is_lts', sa.Boolean(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=True)
    op.create_table('bounding_contours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('is_assembly', sa.Boolean(), nullable=False),
    sa.Column('brep_files', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['bounding_contours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id')
    )
    op.create_table('module_boundary',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('boundary_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['module_boundaries.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'boundary_id')
    )
    op.create_table('module_platform',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'platform_id')
    )
    op.create_table('module_stream',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'stream_id')
    )
    op.create_table('parent_child_module',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('reasons_modules_updating',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('old_module_id', sa.UUID(), nullable=False),
    sa.Column('new_module_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['new_module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['old_module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reasons_modules_updating')
    op.drop_table('parent_child_module')
    op.drop_table('module_stream')
    op.drop_table('module_platform')
    op.drop_table('module_boundary')
    op.drop_table('bounding_contours')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.drop_table('modules')
    op.drop_table('services')
    op.drop_table('module_boundaries')
    op.drop_table('streams')
    op.drop_table('platforms')
    op.drop_table('interface_objects')
    # ### end Alembic commands ###
