"""new 

Revision ID: 2659f322ad93
Revises: 9565cf09900d
Create Date: 2025-01-09 15:21:29.115441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2659f322ad93'
down_revision: Union[str, None] = '9565cf09900d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_modules_name', table_name='modules')
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.create_index('ix_modules_name', 'modules', ['name'], unique=True)
    # ### end Alembic commands ###
