"""Create role table

Revision ID: e79023ee92a0
Revises: 12faf919aaee
Create Date: 2025-01-29 18:28:14.538959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79023ee92a0'
down_revision: Union[str, None] = '12faf919aaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('parent_child_module', sa.Column('role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'parent_child_module', 'module_roles', ['role_id'], ['id'])
    op.drop_column('parent_child_module', 'child_role')
    op.drop_column('parent_child_module', 'child_role_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_child_module', sa.Column('child_role_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('parent_child_module', sa.Column('child_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parent_child_module', type_='foreignkey')
    op.drop_column('parent_child_module', 'role_id')
    op.drop_table('module_roles')
    # ### end Alembic commands ###
